version: '3.8'

services:
  api:
    container_name: werkstuk_api
    build: './api'
    environment:
      POSTGRES_PASSWORD: 
      POSTGRES_USER: 
      POSTGRES_DB:
      POSTGRES_HOST: db
    ports:
       - 3000:3000
    volumes:
      - ./api/src:/usr/api/src

  db:
    container_name: development5_db 
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_PASSWORD: 
      POSTGRES_USER:
      POSTGRES_DB:
    ports:
      - 5432:5432